# Required settings (must be changed)
BOT_TOKEN = "INSERT BOT TOKEN HERE"

# Optional settings (may be changed)
BOT_CMD_PREFIX  = "!"
BOT_ADMIN_ROLE  = 643983323932262410 # GEN role
CHANNEL_TIME_PROTECTION_LENGTH_SECONDS = 60
MESSAGE_DELETE_DELAY_SECONDS = 15
DATABASE_FILENAME = "database.json"
